### ISSUE TITLE
Keeps clicking discord nitro after screenshot

### ISSUE THREAD

**Issue by fiveseven808** [psychopattt/Discord-Remote#1]
I told it to screenshot. It hid the discord window. Keeps trying to repeat the screenshot command, and also clicks the discord nitro button repeatedly.

Could be an unexpected display resolution for your program??

This is using the latest file in releases.

**Comment by psychopattt** [comment]
Nothing uses the display resolution in the latest version, so it should work no matter the resolution of your monitor(s).

I just released version 1.1.0 which includes a lot of improvements and could fix your problem. I did fix a bug related to clicking the nitro button when deleting messages.

This app remains a sort of hack so commands might sometimes fail (that's why there's a built-in failsafe). However, if they always fail, there is definitely a problem. If you still have the same problem on the latest version, I recommend increasing `processDelay` in `Config.ini` to something like 200 or more.

**Comment by fiveseven808** [comment]
I just downloaded it and I ran into way more issues.

First: the exe is not complete, it's referencing scripts outside of the
executable, requiring you to clone the repo and putting the binary in
before running.

Second: The help command doesn't work anymore? It looks like it spit out
the help, then was unable to change back channels, deleted the wrong
message (the help output) and then started copying and erroring out.
I got this as an output:
```
Error - Invalid command: Help - Help
Shows how to us
Error - Invalid command: Shows how to us
```
And then the computer stopped responding.

Where is Config.ini?

**Comment by psychopattt** [comment]
When you start `Discord-Remote.exe`, it should automatically create a directory called `Scripts` in the same directory. Every script referenced by the main script should be extracted and placed in that new `Scripts` directory. To avoid overwriting the scripts every time you launch the executable, only missing files are re-created. This makes it possible to tweak the scripts like you want. However, **if you still have an old version of the scripts, Discord Remote v1.1.0 will try to read them and will break**. In that case, you should delete the `Scripts` directory to let Discord Remote create the new version.

The configuration file is created in the `Scripts` directory. The path to the config from the directory containing `Discord-Remote.exe` is `./Scripts/Config.ini`.

Before releasing any version, I always make sure it works on my side. Every command has been tested and is working on my Windows 10 PC. I can't really do much more testing than that since I don't have multiple computers with different configurations. Here's what I use to test in case it can help you:
- Latest stable version of Discord (Stable 247929) for Windows 10 (it should work with more recent versions)
- Latest version of Discord Remote (currently 1.1.0)
- I then put `Discord-Remote.exe` that I just downloaded from GitHub's releases page into an empty directory
- I start Discord Remote, it creates the `Scripts` directory and starts checking for commands
- I then use the mobile Discord app to send all commands as well as some commands in bulk

This should at least fix the invalid references. If commands still fail often, I recommend increasing `processDelay` in the config. If none of this works, there definitely is a problem, but I'm not sure of what it could be.

**Comment by fiveseven808** [comment]
I was unaware that it unpacked itself in the directory that it ran in (you should probably put a warning)

I left it in my downloads folder which is the same place the new executable was in. This led to the following errors:

![image](https://github.com/psychopattt/Discord-Remote/assets/14186382/819bdbf5-c754-41b9-a32a-6aea96bdb475)

Putting the exe in a new folder did solve the problems. 


Updating processDelay to 500 seems to have solved a lot of my issues. The program seems way more reliable. I don't know what factors go into determining a good processDelay, but maybe the default should be a bit higher than 100?

**Comment by psychopattt** [comment]
I'm trying to keep `processDelay` as low as possible since the program is already quite slow. Everything works on my PC with 100. The ideal delay probably varies greatly between computers, so I'd prefer having the default set to the value I'm using to test. This way, I'm sure the program works at a decent speed and it's quick when I'm adding new features or fixing bugs.

I'll update the Readme to make it clear that the old `Scripts` directory should be deleted when installing a new version of Discord Remote.
